[package]
name = "rust_jwt_actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-web-lab = "0.22.0"
uuid = { version = "1.11.0", features = ["v4"] }
base64 = "0.22.1"
lazy_static = "1.5.0"